version: "3"

services:
  # nginx:
  #   container_name: nginx
  #   image: "nginx:alpine"
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
  node:
    container_name: node
    image: "kimoo1/teachercan-back"
    env_file:
      - "./.env"
    ports:
      - "5000:4000"
    command: npm run rebuild
